name: Deploy Node.js backend to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Change "main" si ta branche s'appelle autrement

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # adapte à ta version Node

      - name: Install dependencies
        run: npm install

      - name: Create deployment package
        run: zip -r app.zip . -x "*.git*" "node_modules/*" ".github/*"

      - name: Deploy to AWS Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: mobileterrain-backend
          environment_name: mobileterrain-env
          region: us-east-1  # adapte à ta région AWS
          deployment_package: app.zip